module.exports = {
  apps: [
    {
      name: 'mec-poa-backend',
      script: 'npx',
      args: 'tsx watch src/server.ts',
      cwd: './backend',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ignore_watch: ['node_modules', 'dist', '*.log'],
      env: {
        NODE_ENV: 'development',
        PORT: 3002,
        DB_HOST: 'localhost',
        DB_PORT: '5433',
        DB_NAME: 'mec_poa',
        DB_USER: 'postgres',
        DB_PASSWORD: 'postgres',
        JWT_SECRET: process.env.JWT_SECRET || 'desenvolvimento-jwt-secret-change-in-production',
        JWT_EXPIRES_IN: '7d',
        CORS_ORIGIN: process.env.CORS_ORIGIN || 'http://localhost:5173',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3002,
        DB_HOST: process.env.DB_HOST || 'localhost',
        DB_PORT: process.env.DB_PORT || '5433',
        DB_NAME: process.env.DB_NAME || 'mec_poa',
        DB_USER: process.env.DB_USER || 'postgres',
        DB_PASSWORD: process.env.DB_PASSWORD || 'postgres',
        JWT_SECRET: process.env.JWT_SECRET || 'change-me-in-production',
        JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || '7d',
        CORS_ORIGIN: process.env.CORS_ORIGIN || 'http://localhost:5173',
      },
      error_file: './logs/backend-error.log',
      out_file: './logs/backend-out.log',
      log_file: './logs/backend-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '1G',
    },
    {
      name: 'mec-poa-frontend',
      script: 'npm',
      args: 'run dev',
      cwd: './frontend',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      ignore_watch: ['node_modules', 'dist', '*.log'],
      env: {
        NODE_ENV: 'development',
      },
      env_production: {
        NODE_ENV: 'production',
      },
      error_file: './logs/frontend-error.log',
      out_file: './logs/frontend-out.log',
      log_file: './logs/frontend-combined.log',
      time: true,
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '1G',
    },
  ],
};
